### ISSUE TITLE
Secrets input doesn't work

### ISSUE THREAD

**Issue by HuyAms** [superfly/fly-pr-review-apps#19]
Hi, 

I use this action to deploy my app and it works perfectly. However, the action doesn't add any secret to my app. Is there anything wrong with my syntax?

Here is my GitHub action
```
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "./web/fly.toml"
          field: "app"

      - name: 🚀 Deploy Preview
        id: deploy
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          path: "./web"
          name: deploy-preview-${{ github.event.number }}--${{ steps.app_name.outputs.value }}
          region: fra
          org: test
          image: "registry.fly.io/${{ steps.app_name.outputs.value }}:${{ needs.extract_branch_name.outputs.value }}-${{ github.sha }}"
          secrets: SANITY_DATASET=staging
```

My app doesn't show any secret
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/26871154/202707150-35b9a17a-06a0-46fc-9266-face2ce2b82b.png">
