### ISSUE TITLE
Update with flyctl switched to searching for images remotely

### ISSUE THREAD

**Issue by jakelacey2012** [superfly/fly-pr-review-apps#66]
```
      - name: Build elixir image
        run: docker build -t custom-image-elixir:1.16 -f Dockerfile .

      - name: Deploy PR app to Fly.io

        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: pr-${{ github.event.number }}-savvychef
          image: custom-image-elixir:1.16
```
