### ISSUE TITLE
New machines being created on each push

### ISSUE THREAD

**Issue by tylerhunt** [superfly/fly-pr-review-apps#74]
Each push to the PR is causing new Fly machines to be spun up and the old ones are never destroyed.

This shows a PR that has had 3 pushes. The expected behavior is to only have one `app` and one `worker` machine.

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/7f789d7d-3ab3-438a-b40a-d1d44d531a11" />

**Comment by tekknolagi** [comment]
I just hit this and only found out when my CI failed because I couldn't create any more machines. It would be cool if there was a way to create ephemeral machines, or automatically tear down on the PR closing.

**Comment by tekknolagi** [comment]
I fixed the lingering machines after PR close by manually destroying apps:

```yml
name: Deploy preview on fly.io

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, edited, synchronize, closed]

jobs:
  staging_app:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      # ...

  clean_up_app:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh
      - name: Clean up app
        run: ~/.fly/bin/flyctl app destroy --yes bernsteinbear-com-pr-${{ github.event.number }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

**Comment by tylerhunt** [comment]
That functionality is [already handled here](https://github.com/superfly/fly-pr-review-apps/blob/main/entrypoint.sh#L35-L39) when the type is `closed`:

```
on:
  pull_request:
    types:
      - closed
```
